[Collectibles]
SpaceshipPart=true
LetterScrap=true
NuclearWaste=true
SubmarinePart=true
HiddenPackage=true
MonkeyMosaic=true
PeyotePlant=true
EpsilonTract=true
UnderTheBridge=true
KnifeFlight=true
StuntJump=true

[Keybinds]
; Virtual-key code for toggling all collectibles on/off
; Default: F11
; https://github.com/sepehrsohrabi/Decimal-Virtual-Key-Codes
ToggleKey=122

[Compatibility]
; Values for enhanced 1.72
; Only used as fallback if pattern finder fails
; These values may need to be updated for future game versions if Rockstar decides to recompile scripts
; You can look them up in decompiled scripts of the game, for example in flyunderbridges.c
GlobalVar=114931
Offset=10056

; Resources:
; GTA V Enhanced Decompiled Scripts: https://github.com/acidlabsdev/gtav-enhanced-scripts
; GTA V Decompiled Scripts: https://github.com/calamity-inc/GTA-V-Decompiled-Scripts
;
; Example:
;
;  void func_1() // Position - 0x52F (1327)
;   {
;     BOOL flag;
;  
;     if (iLocal_29 < 32)
;       flag = IS_BIT_SET(Global_114931.f_10056.f_96, iLocal_29);
;     else if (iLocal_29 < 64)
;       flag = IS_BIT_SET(Global_114931.f_10056.f_97, iLocal_29 - 32);
;     else
;       flag = IS_BIT_SET(Global_114931.f_10056.f_98, iLocal_29 - 64);
;  
;     if (flag)
;     {
;     }
;     else
;     {
;       if (!bLocal_265)
;       {
;         if (bLocal_36)
;           STATS::STAT_INCREMENT(joaat("SP_KNIFE_FLIGHTS_COUNT"), 1f);
;         else
;           STATS::STAT_INCREMENT(joaat("SP_UNDER_THE_BRIDGE_COUNT"), 1f);
;  
;         func_3(_GET_CURRENT_PLAYER_CHARACTER(), 5, 3);
;         func_2();
;       }
;  
;       if (iLocal_29 < 32)
;         MISC::SET_BIT(&(Global_114931.f_10056.f_96), iLocal_29);
;       else if (iLocal_29 < 64)
;         MISC::SET_BIT(&(Global_114931.f_10056.f_97), iLocal_29 - 32);
;       else
;         MISC::SET_BIT(&(Global_114931.f_10056.f_98), iLocal_29 - 64);
;  
;       Global_98874 = 1;
;       func_31();
;       bLocal_27 = true;
;     }
;  
;     return;
;   }
